#!/usr/bin/env bash

black='\e[0;30m'
red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
blue='\e[0;34m'
purple='\e[0;35m'
cyan='\e[0;36m'
white='\e[0;37m'

b_black='\e[1;30m'
b_red='\e[1;31m'
b_green='\e[1;32m'
b_yellow='\e[1;33m'
b_blue='\e[1;34m'
b_purple='\e[1;35m'
b_cyan='\e[1;36m'
b_white='\e[1;37m'

on_black='\e[40m'
on_red='\e[41m'
on_green='\e[42m'
on_yellow='\e[43m'
on_blue='\e[44m'
on_purple='\e[45m'
on_cyan='\e[46m'
on_white='\e[47m'

reset='\e[0m'

arc_dr='\342\225\255'
arc_ur='\342\225\260'
box_h='\342\224\200'
box_heavy_r='\342\225\274'
bracket_l='\342\246\227'
bracket_r='\342\246\230'

line_1="$b_green$arc_dr$bracket_l$b_white\u$b_green@$b_blue\h$b_green$bracket_r$box_h$bracket_l$b_white\w$b_green$bracket_r"
line_2="$b_green$arc_ur$box_heavy_r \$ $reset"

PS1="$line_1\n$line_2"
